- .gitignore
- src/toniarts/opendungeonkeeper/tools/modelviewer/ModelViewer.java
You can now select Maps directly and view it. Because these are already
big, they are not resized and there is no rotation. But Wireframe is
still possible.
> Support for Maps

- src/toniarts/opendungeonkeeper/tools/convert/BankMapLoader.java
- src/toniarts/opendungeonkeeper/tools/convert/KmfModelLoader.java
- src/toniarts/opendungeonkeeper/tools/convert/MapLoader.java
- src/toniarts/opendungeonkeeper/tools/convert/SdtExtractor.java
- src/toniarts/opendungeonkeeper/tools/convert/TextureExtractor.java
- src/toniarts/opendungeonkeeper/tools/convert/WadExtractor.java
- src/toniarts/opendungeonkeeper/tools/modelviewer/ModelViewer.java
very unlikely that all conditions are true at the same time...
> Fix wrong operator in argument

- src/toniarts/opendungeonkeeper/tools/convert/str/StrFile.java
Looks like an really easy change. 
Tested it with all textfiles in german.
> sort offsets (german offsets aren't sorted correctly)

- src/toniarts/opendungeonkeeper/tools/convert/AssetsConverter.java
- src/toniarts/opendungeonkeeper/tools/convert/wad/WadFile.java
This PR also extracts `EngineTextures.WAD` and `FrontEnd.WAD` to the Textures directory.
It also has a small bugfix for reading wads and extracting them.
> Extract texture wads

- src/toniarts/opendungeonkeeper/tools/convert/map/loader/MapLoader.java
This fixes water and claimed tiles. Best seen on Asmodeus.
**Before:**
**After:**
> Fix for wrong tiles because of different diagonal tile.

- assets/MatDefs/Video/MovieMaterial.j3md
- assets/Shaders/Video/MovieMaterial.frag
- assets/Shaders/Video/MovieMaterial.vert
- nbproject/configs/TGQ.properties
- src/toniarts/openkeeper/Main.java
- src/toniarts/openkeeper/tools/convert/BitReader.java
- src/toniarts/openkeeper/video/MovieMaterial.java
- src/toniarts/openkeeper/video/MovieState.java
- src/toniarts/openkeeper/video/TgqPlayer.java
- src/toniarts/openkeeper/video/tgq/EAAudioFrame.java
- src/toniarts/openkeeper/video/tgq/EAAudioHeader.java
- src/toniarts/openkeeper/video/tgq/TgqFile.java
- src/toniarts/openkeeper/video/tgq/TgqFrame.java
> Feature 31

- assets/Interface/MainMenu.xml
- assets/Interface/MyControls.xml
- assets/Interface/ScrollpanelStyle.xml
- src/toniarts/openkeeper/game/state/MainMenuState.java
As the title already says, this is the implementation of the movies menu.
What's done so far:
- dynamic generation of the movie buttons
- stub for checking if the movie is unlocked
- showing a message if the cutscene is still locked
- linked the trailer in the extras menu to play the dk3-trailer
Fixes #57
> Implement movie menu

- assets/Interface/MainMenu.xml
- assets/Interface/MyControls.xml
- src/toniarts/openkeeper/game/state/MainMenuState.java
Read the hiscore list and display them in the menu
Fixes #56.
> Implement hiscore list

- assets/Interface/MainMenu.xml
It's probably better to use the small font (as the other one is way too big on 800x600).
Also remove a not needed effect i put in with the last pr
> change the credit text size (it's too big on small resolution)

- src/toniarts/openkeeper/world/MapLoader.java
- src/toniarts/openkeeper/world/room/CombatPit.java
- src/toniarts/openkeeper/world/room/DoubleQuad.java
- src/toniarts/openkeeper/world/room/HeroGateThreeByOne.java
- src/toniarts/openkeeper/world/room/HeroGateTwoByTwo.java
- src/toniarts/openkeeper/world/room/Prison.java
- src/toniarts/openkeeper/world/room/Quad.java
- src/toniarts/openkeeper/world/room/RoomConstructor.java
- src/toniarts/openkeeper/world/room/RoomInstance.java
- src/toniarts/openkeeper/world/room/StoneBridge.java
- src/toniarts/openkeeper/world/room/Temple.java
- src/toniarts/openkeeper/world/room/WoodenBridge.java
This is a quick and dirty cherry pick of ArchDemons changes to the room construction.
Helps #36
> Room construction by ArchDemons

- assets/Interface/MainMenu.xml
- assets/Interface/MyControls.xml
- src/toniarts/openkeeper/game/data/Level.java
- src/toniarts/openkeeper/game/state/MainMenuState.java
- src/toniarts/openkeeper/world/room/HeroGateFrontEnd.java
- src/toniarts/openkeeper/world/room/control/FrontEndLevelControl.java
- MPD Level names are translated now
- Level, Secret level and MPD are using the same campaign screen
- Small GUI Improvements
> Implement MPD and Secret level selection to main menu

- src/toniarts/openkeeper/world/MapLoader.java
The hero stone needs also to be build like the stone bridge (used in Maps like Alcatraz)
> construct hero stone bridge also as a stone bridge

- src/toniarts/openkeeper/game/state/GameState.java
- src/toniarts/openkeeper/tools/convert/map/KwdFile.java
- src/toniarts/openkeeper/tools/convert/map/Map.java
- src/toniarts/openkeeper/tools/convert/map/Tile.java
- src/toniarts/openkeeper/world/GameCreature.java
- src/toniarts/openkeeper/world/MapLoader.java
- src/toniarts/openkeeper/world/MapThumbnailGenerator.java
- src/toniarts/openkeeper/world/PathFinder.java
- src/toniarts/openkeeper/world/ThingLoader.java
Imps are now loaded and displayed
> Feature 15

- assets/Interface/CreditsControl.xml
- assets/Interface/MainMenu.xml
- assets/Interface/MyControls.xml
- assets/Interface/ScrollbarStyle.xml
I tested at resolutions 640x480 and 800x600 - it looks great
> Gui update

- src/toniarts/openkeeper/gui/Cursor.java
- src/toniarts/openkeeper/gui/CursorFactory.java
- src/toniarts/openkeeper/tools/modelviewer/ModelViewer.java
You can't slap your creatures without the correct mouse cursor! ;).
What's done:
* refactored the current Cursorfactory (since the existing cursors shared quite a lot code)
* added the rest of the cursors
* fixed the width issue (just needed to be a multiple of 16)
* fixed the empty line issue (same problem with multiple of 16)
What's not done:
* `NO_SPELL_POSSESS` and `SPELL_POSSESS` have some issues because the file format, so i left them open. If we can't fix them we just build our own, as they are pretty easy.
* The hotspot point may not be correct, they were just a random guess
Should help #98, #97
> Mouse cursors

- .travis.yml
- build.gradle
This integrates Travis CI.
Currently it just checks for compile time errors, later it should also be easier to integrate automatic tests and run them.
See https://travis-ci.org/ufdada/OpenKeeper as example.
You may need to enable your repository so that travis checks for it.
> Set up continues integration

- assets/Interface/GameHUD.xml
I played with possession is very rare, could have missed something
> Feature 110

- assets/Interface/GameHUD.xml
- src/toniarts/openkeeper/game/state/PlayerState.java
- src/toniarts/openkeeper/tools/convert/map/KwdFile.java
- src/toniarts/openkeeper/view/PlayerCameraState.java
- src/toniarts/openkeeper/view/PlayerInteractionState.java
- src/toniarts/openkeeper/view/PossessionCamera.java
- src/toniarts/openkeeper/view/PossessionCameraState.java
- src/toniarts/openkeeper/view/PossessionInteractionState.java
known bugs:
* animation of rooms, spells, traps and doors buttons not work after leaving the possession
* dublicated contorl triggers (player state and posssesion state). I fixed it, but ugly. Need refactor.
> Feature 109

- src/toniarts/openkeeper/game/data/Settings.java
- src/toniarts/openkeeper/game/state/MainMenuState.java
- src/toniarts/openkeeper/game/state/PlayerState.java
- src/toniarts/openkeeper/view/PlayerCamera.java
- src/toniarts/openkeeper/view/PlayerCameraState.java
- src/toniarts/openkeeper/world/MapLoader.java
added camera position limits
added camera rotation
added skipping game cinematic
> added camera start position and direction

- src/toniarts/openkeeper/Main.java
- src/toniarts/openkeeper/ai/creature/CreatureState.java
- src/toniarts/openkeeper/game/state/GameState.java
- src/toniarts/openkeeper/game/state/PlayerState.java
- src/toniarts/openkeeper/tools/convert/map/Player.java
- src/toniarts/openkeeper/utils/Utils.java
- src/toniarts/openkeeper/view/PlayerInteractionState.java
- src/toniarts/openkeeper/world/EntityInstance.java
- src/toniarts/openkeeper/world/MapData.java
- src/toniarts/openkeeper/world/MapLoader.java
- src/toniarts/openkeeper/world/ThingLoader.java
- src/toniarts/openkeeper/world/TileData.java
- src/toniarts/openkeeper/world/WorldHandler.java
- src/toniarts/openkeeper/world/creature/CreatureControl.java
- src/toniarts/openkeeper/world/creature/CreatureLoader.java
- src/toniarts/openkeeper/world/creature/pathfinding/MapConnection.java
- src/toniarts/openkeeper/world/creature/pathfinding/MapDistance.java
- src/toniarts/openkeeper/world/creature/pathfinding/MapIndexedGraph.java
- src/toniarts/openkeeper/world/creature/pathfinding/MapPathFinder.java
- src/toniarts/openkeeper/world/creature/steering/AbstractCreatureSteeringControl.java
- src/toniarts/openkeeper/world/creature/steering/CreatureLocation.java
- src/toniarts/openkeeper/world/creature/steering/CreatureRayCastCollisionDetector.java
- src/toniarts/openkeeper/world/room/FiveByFiveRotated.java
- src/toniarts/openkeeper/world/room/GenericRoom.java
- src/toniarts/openkeeper/world/room/ThreeByThree.java
Very crude code here & there, a bit prototyping, big levels (amount of creatures) are now slow to load
> Feature 88

- src/toniarts/openkeeper/game/state/PlayerState.java
- src/toniarts/openkeeper/world/MapData.java
- src/toniarts/openkeeper/world/MapLoader.java
- src/toniarts/openkeeper/world/TileData.java
- src/toniarts/openkeeper/world/WorldState.java
- src/toniarts/openkeeper/world/room/CombatPit.java
- src/toniarts/openkeeper/world/room/DoubleQuad.java
- src/toniarts/openkeeper/world/room/FiveByFiveRotated.java
- src/toniarts/openkeeper/world/room/GenericRoom.java
- src/toniarts/openkeeper/world/room/HeroGate.java
- src/toniarts/openkeeper/world/room/HeroGateFrontEnd.java
- src/toniarts/openkeeper/world/room/HeroGateThreeByOne.java
- src/toniarts/openkeeper/world/room/HeroGateTwoByTwo.java
- src/toniarts/openkeeper/world/room/Normal.java
- src/toniarts/openkeeper/world/room/Prison.java
- src/toniarts/openkeeper/world/room/Quad.java
- src/toniarts/openkeeper/world/room/RoomConstructor.java
- src/toniarts/openkeeper/world/room/RoomInstance.java
- src/toniarts/openkeeper/world/room/StoneBridge.java
- src/toniarts/openkeeper/world/room/Temple.java
- src/toniarts/openkeeper/world/room/ThreeByThree.java
- src/toniarts/openkeeper/world/room/WoodenBridge.java
* properly tagging tiles with room wall
* some refactoring of room construction
> Map loader

- src/toniarts/openkeeper/tools/convert/map/KwdFile.java
- src/toniarts/openkeeper/world/MapLoader.java
- src/toniarts/openkeeper/world/effect/EffectManager.java
- src/toniarts/openkeeper/world/room/FiveByFiveRotated.java
- src/toniarts/openkeeper/world/room/GenericRoom.java
- src/toniarts/openkeeper/world/room/RoomConstructor.java
- src/toniarts/openkeeper/world/room/control/PlugControl.java
effect loader with test on dungeon heart
added dungeon heart plug
added dungeon heart destroyed model
added dungeon heart decayed model
> Effect Loader (initial state)

- src/toniarts/openkeeper/world/MapData.java
- src/toniarts/openkeeper/world/MapLoader.java
- src/toniarts/openkeeper/world/QuadConstructor.java
- src/toniarts/openkeeper/world/TileConstructor.java
- src/toniarts/openkeeper/world/WaterConstructor.java
* fixed water bed construction
* small refactoring of TileConstructor
> fixed water bed construction

- src/toniarts/openkeeper/game/player/PlayerGoldControl.java
- src/toniarts/openkeeper/game/player/PlayerManaControl.java
- src/toniarts/openkeeper/game/state/CheatState.java
- src/toniarts/openkeeper/view/PlayerInteractionState.java
> Implement cheats

- src/toniarts/openkeeper/Main.java
- src/toniarts/openkeeper/setup/DKFolderSelector.java
- src/toniarts/openkeeper/tools/convert/AssetsConverter.java
- src/toniarts/openkeeper/tools/convert/BankMapLoader.java
- src/toniarts/openkeeper/tools/convert/Bf4Extractor.java
- src/toniarts/openkeeper/tools/convert/KmfModelLoader.java
- src/toniarts/openkeeper/tools/convert/MapLoader.java
- src/toniarts/openkeeper/tools/convert/SdtExtractor.java
- src/toniarts/openkeeper/tools/convert/TextureExtractor.java
- src/toniarts/openkeeper/tools/convert/WadExtractor.java
- src/toniarts/openkeeper/tools/convert/map/KwdFile.java
- src/toniarts/openkeeper/tools/convert/sound/SdtFile.java
- src/toniarts/openkeeper/tools/convert/textures/enginetextures/EngineTexturesFile.java
- src/toniarts/openkeeper/tools/convert/wad/WadFile.java
- src/toniarts/openkeeper/tools/modelviewer/ModelViewer.java
- src/toniarts/openkeeper/utils/PathUtils.java
- src/toniarts/openkeeper/utils/SettingUtils.java
I tried to squash the duplicated code and refactored it into two util-classes.
Also the dungeon keeper folder is now just an optional parameter.
> Dungeon keeper folder & settings

- src/toniarts/openkeeper/ai/creature/CreatureState.java
- src/toniarts/openkeeper/game/data/Keeper.java
- src/toniarts/openkeeper/game/logic/CreatureSpawnLogicState.java
- src/toniarts/openkeeper/game/player/AbstractPlayerControl.java
- src/toniarts/openkeeper/game/player/PlayerCreatureControl.java
- src/toniarts/openkeeper/game/player/PlayerRoomControl.java
- src/toniarts/openkeeper/game/player/PlayerTriggerControl.java
- src/toniarts/openkeeper/game/state/GameState.java
- src/toniarts/openkeeper/game/state/PlayerState.java
- src/toniarts/openkeeper/game/trigger/TriggerControl.java
- src/toniarts/openkeeper/tools/convert/map/KwdFile.java
- src/toniarts/openkeeper/world/ThingLoader.java
- src/toniarts/openkeeper/world/WorldState.java
- src/toniarts/openkeeper/world/creature/CreatureControl.java
- src/toniarts/openkeeper/world/creature/CreatureLoader.java
- src/toniarts/openkeeper/world/listener/RoomListener.java
- src/toniarts/openkeeper/world/room/FiveByFiveRotated.java
- src/toniarts/openkeeper/world/room/GenericRoom.java
- src/toniarts/openkeeper/world/room/ICreatureEntrance.java
- src/toniarts/openkeeper/world/room/ThreeByThree.java
Resolves #149. As well as implements room ownership as a better manageable concept. Many triggers are also now implemented.
> Player stuff

- assets/Interface/MainMenu.xml
- src/toniarts/openkeeper/game/MapSelector.java
- src/toniarts/openkeeper/game/state/MainMenuState.java
some isolation of map selection
> Map Selector

- src/toniarts/openkeeper/utils/FullMoon.java
- src/toniarts/openkeeper/world/room/HeroGateFrontEnd.java
Fixes #48 
This is quite a hackish conversion from c, but it seems to work.
KeeperFX also has an implementation, which is quite complicated (see bflib_pom.cpp)
> Implement full moon

- src/toniarts/openkeeper/game/control/Control.java
- src/toniarts/openkeeper/game/control/IControl.java
- src/toniarts/openkeeper/game/data/Keeper.java
- src/toniarts/openkeeper/game/logic/GameLogicThread.java
- src/toniarts/openkeeper/game/player/PlayerCameraRotateControl.java
- src/toniarts/openkeeper/game/player/PlayerCreatureControl.java
- src/toniarts/openkeeper/game/player/PlayerManaControl.java
- src/toniarts/openkeeper/game/player/PlayerTriggerControl.java
- src/toniarts/openkeeper/game/state/GameState.java
- src/toniarts/openkeeper/game/state/PlayerState.java
- src/toniarts/openkeeper/game/trigger/TriggerControl.java
- src/toniarts/openkeeper/view/PlayerCamera.java
- src/toniarts/openkeeper/view/PlayerCameraState.java
- src/toniarts/openkeeper/view/PlayerInteractionState.java
- src/toniarts/openkeeper/world/PathFinder.java
- src/toniarts/openkeeper/world/QuadConstructor.java
added camera rotation control around action point
PlayerTriggerControl and PlayerManaControl moved to Keeper
fixed TriggerControl action and activation
removed debug interactions (claiming and digging)
some known bugs: 
crash game in level 1 (access from other thread). I think this is some trigger action
> Feature 170

- src/toniarts/openkeeper/Main.java
- src/toniarts/openkeeper/game/state/MainMenuState.java
- src/toniarts/openkeeper/tools/convert/AssetsConverter.java
- src/toniarts/openkeeper/tools/convert/BankMapLoader.java
- src/toniarts/openkeeper/tools/convert/Bf4Extractor.java
- src/toniarts/openkeeper/tools/convert/SdtExtractor.java
- src/toniarts/openkeeper/tools/convert/WadExtractor.java
- src/toniarts/openkeeper/tools/convert/map/KwdFile.java
- src/toniarts/openkeeper/tools/modelviewer/ModelViewer.java
- src/toniarts/openkeeper/utils/PathUtils.java
Cherry picked and rebased the changes from #192
> Dkfolder NullpointerException

- assets/Interface/MainMenu.xml
- src/toniarts/openkeeper/game/data/Settings.java
- src/toniarts/openkeeper/game/network/NetworkClient.java
- src/toniarts/openkeeper/game/network/NetworkServer.java
- src/toniarts/openkeeper/game/network/ServerListener.java
- src/toniarts/openkeeper/game/network/message/MessagePlayerInfo.java
- src/toniarts/openkeeper/game/network/message/MessageServerInfo.java
- src/toniarts/openkeeper/game/state/MainMenuState.java
- src/toniarts/openkeeper/utils/Utils.java
A bit touch ups to networking. Mainly the memory thing, it is the most important feature of the whole game.
> Networking stuff

- src/toniarts/openkeeper/game/data/Keeper.java
- src/toniarts/openkeeper/game/logic/CreatureSpawnLogicState.java
- src/toniarts/openkeeper/game/logic/GameLogicThread.java
- src/toniarts/openkeeper/game/player/AbstractPlayerControl.java
- src/toniarts/openkeeper/game/player/PlayerCreatureControl.java
- src/toniarts/openkeeper/game/player/PlayerManaControl.java
- src/toniarts/openkeeper/game/player/PlayerRoomControl.java
- src/toniarts/openkeeper/game/state/GameState.java
- src/toniarts/openkeeper/game/state/MainMenuState.java
- src/toniarts/openkeeper/game/state/PlayerState.java
- src/toniarts/openkeeper/game/trigger/TriggerControl.java
- src/toniarts/openkeeper/tools/convert/map/KwdFile.java
- src/toniarts/openkeeper/world/ThingLoader.java
- src/toniarts/openkeeper/world/WorldState.java
Fixes all (?) concurrency issues, and many issues with MPD maps as well as the basic level data such as availabilities
> Concurrency issues

- src/toniarts/openkeeper/tools/modelviewer/ModelViewer.java
- src/toniarts/openkeeper/world/creature/CreatureLoader.java
Now both ModelViewer and CreatureLoader use the same method to determine if the LoopMode is CYCLE or LOOP
> refactored setting op LoopMode CYCLE and LOOP

- src/toniarts/openkeeper/tools/modelviewer/ModelViewer.java
- src/toniarts/openkeeper/world/effect/EffectManagerState.java
Some slight adjustments for pr #213 and #207
> Modelviewer effects

- src/toniarts/openkeeper/game/action/ActionPoint.java
- src/toniarts/openkeeper/game/action/ActionPointState.java
- src/toniarts/openkeeper/game/action/FlashControl.java
- src/toniarts/openkeeper/game/control/Control.java
- src/toniarts/openkeeper/game/player/PlayerCameraControl.java
- src/toniarts/openkeeper/game/trigger/TriggerControl.java
- src/toniarts/openkeeper/world/MapLoader.java
- src/toniarts/openkeeper/world/TileData.java
- src/toniarts/openkeeper/world/WorldState.java
- src/toniarts/openkeeper/world/control/FlashTileControl.java
There are two different ways to flash tiles (in each commit). What way is better ?
* Control on ActionPoint
* Control on WorldState
> Feature 137

- src/toniarts/openkeeper/gui/Cursor.java
- src/toniarts/openkeeper/gui/CursorFactory.java
+ added support BGR8 cursor image format
* fixed idle cursor hotspot
> Fix cursors to support other formats than RGBA 32-bit

- assets/Interface/GameHUD.xml
- src/toniarts/openkeeper/game/console/ConsoleInputListener.java
- src/toniarts/openkeeper/game/console/ConsoleState.java
- src/toniarts/openkeeper/game/console/GameConsole.java
- src/toniarts/openkeeper/game/data/Settings.java
- src/toniarts/openkeeper/game/state/PlayerState.java
- src/toniarts/openkeeper/view/PlayerInteractionState.java
> Feature 112

- assets/Interface/CustomTabControl.xml
- assets/Interface/GameHUD.xml
- assets/Interface/HintStyle.xml
- assets/Interface/MyControls.xml
- src/toniarts/openkeeper/game/state/PlayerState.java
- src/toniarts/openkeeper/gui/nifty/CustomTabControl.java
- src/toniarts/openkeeper/gui/nifty/CustomTabGroupControl.java
- src/toniarts/openkeeper/view/PlayerInteractionState.java
I tried to add all tooltips and balloon information i could find to the hud.
I also added a dummy for the player information:
> Tooltip improvements and implementing balloon information

- assets/Interface/CreditsControl.xml
- assets/Interface/GameHUD.xml
- assets/Interface/MainMenu.xml
- assets/Interface/MyControls.xml
- src/toniarts/openkeeper/Main.java
- src/toniarts/openkeeper/game/console/ConsoleState.java
- src/toniarts/openkeeper/game/console/GameConsole.java
- src/toniarts/openkeeper/game/data/Level.java
- src/toniarts/openkeeper/game/data/Settings.java
- src/toniarts/openkeeper/game/state/GameState.java
- src/toniarts/openkeeper/game/state/IMainMenuScreenController.java
- src/toniarts/openkeeper/game/state/IPlayerScreenController.java
- src/toniarts/openkeeper/game/state/MainMenuScreenController.java
- src/toniarts/openkeeper/game/state/MainMenuState.java
- src/toniarts/openkeeper/game/state/PlayerScreenController.java
- src/toniarts/openkeeper/game/state/PlayerState.java
- src/toniarts/openkeeper/game/state/SystemMessageState.java
- src/toniarts/openkeeper/game/state/loading/SingleBarLoadingState.java
- src/toniarts/openkeeper/gui/nifty/message/MessageBoxControl.java
- src/toniarts/openkeeper/gui/nifty/message/SystemMessageControl.java
- src/toniarts/openkeeper/tools/convert/AssetsConverter.java
- src/toniarts/openkeeper/tools/modelviewer/ModelViewer.java
- src/toniarts/openkeeper/view/PlayerCameraState.java
- src/toniarts/openkeeper/view/PlayerInteractionState.java
- src/toniarts/openkeeper/view/PossessionCameraState.java
- src/toniarts/openkeeper/world/MapLoader.java
- src/toniarts/openkeeper/world/WorldState.java
How to use:
if you place action (onClick e.g.) in xml file, you must change interface of linked Screen controller
Incomplete:
Some protected fields in state class. But looks better than it was
> Feature 81

- src/toniarts/openkeeper/view/KeeperHand.java
- src/toniarts/openkeeper/view/KeeperHandQueue.java
- src/toniarts/openkeeper/view/PlayerInteractionState.java
- src/toniarts/openkeeper/world/control/IInteractiveControl.java
- src/toniarts/openkeeper/world/creature/CreatureControl.java
- src/toniarts/openkeeper/world/object/ObjectControl.java
* refactor of PlayerInteractionState. Keeper hand in own class
+ added keeper hand item icons queue.
> Keeper Hand

- src/toniarts/openkeeper/game/FunnyCameraContol.java
- src/toniarts/openkeeper/game/state/PlayerScreenController.java
- src/toniarts/openkeeper/game/state/PlayerState.java
- src/toniarts/openkeeper/view/PlayerCamera.java
- src/toniarts/openkeeper/view/PlayerCameraState.java
- src/toniarts/openkeeper/view/PlayerInteractionState.java
- src/toniarts/openkeeper/view/PossessionCamera.java
- src/toniarts/openkeeper/view/PossessionCameraControl.java
- src/toniarts/openkeeper/view/PossessionCameraState.java
- src/toniarts/openkeeper/view/PossessionInteractionState.java
- src/toniarts/openkeeper/world/object/HighlightControl.java
added FunnyCameraContol (follows the target)
added HighLightControl (marks object. In next update will work properly)
added PossessionCameraControl entrance and exit from possession
fixed Possession selection creature
P.S. FunnyCameraContol is temporary solution (for fun) ^_^
> Small Controls Update

- assets/Interface/MainMenu.xml
- src/toniarts/openkeeper/game/MapSelector.java
- src/toniarts/openkeeper/game/data/CustomLevel.java
- src/toniarts/openkeeper/game/data/CustomMPDLevel.java
- src/toniarts/openkeeper/game/data/GeneralLevel.java
- src/toniarts/openkeeper/game/data/Level.java
- src/toniarts/openkeeper/game/state/MainMenuScreenController.java
- src/toniarts/openkeeper/game/state/MainMenuState.java
- src/toniarts/openkeeper/tools/convert/map/GameLevel.java
Resolves #203 
This could've been such an easy task to do, but finding out that the whole text table thing in the level data was probably never really used (at least in official maps) and hard coded into the executable was quite a pain in the ass.
> My pet dungeon - custom level selection

- src/toniarts/openkeeper/tools/convert/AssetsConverter.java
- src/toniarts/openkeeper/tools/convert/ConversionUtils.java
- src/toniarts/openkeeper/tools/convert/SoundExtractor.java
- src/toniarts/openkeeper/tools/convert/bf4/Bf4File.java
- src/toniarts/openkeeper/tools/convert/kmf/KmfFile.java
- src/toniarts/openkeeper/tools/convert/map/KwdFile.java
- src/toniarts/openkeeper/tools/convert/sound/BankMapFile.java
- src/toniarts/openkeeper/tools/convert/sound/BankMapFileEntry.java
- src/toniarts/openkeeper/tools/convert/sound/SFChunk.java
- src/toniarts/openkeeper/tools/convert/sound/SFFile.java
- src/toniarts/openkeeper/tools/convert/sound/SdtFile.java
- src/toniarts/openkeeper/tools/convert/sound/SdtFileEntry.java
- src/toniarts/openkeeper/tools/convert/sound/SfxMapFile.java
- src/toniarts/openkeeper/tools/convert/spr/SprFile.java
- src/toniarts/openkeeper/tools/convert/str/StrFile.java
- src/toniarts/openkeeper/tools/convert/wad/WadFile.java
- src/toniarts/openkeeper/video/tgq/TgqFile.java
Sound extractor prepared to convert all audio data
added SF2 file format decoder
fixed Wav decode from SDT archive
refactor ConversionUtils
refactor BankMap, SfxMap file decoder (decoded some values)
> Sound patch

- src/toniarts/openkeeper/view/PlayerInteractionState.java
- src/toniarts/openkeeper/view/selection/SelectionArea.java
- src/toniarts/openkeeper/view/selection/SelectionHandler.java
refactor PlayerInteractionState
refactor selectionHandler controls visual selection box now
> New PlayerInteractionState

- src/toniarts/openkeeper/game/state/GameState.java
- src/toniarts/openkeeper/game/task/AbstractTask.java
- src/toniarts/openkeeper/game/task/TaskManager.java
- src/toniarts/openkeeper/game/task/worker/DigTileTask.java
- src/toniarts/openkeeper/game/trigger/door/DoorTriggerControl.java
- src/toniarts/openkeeper/game/trigger/door/DoorTriggerState.java
- src/toniarts/openkeeper/tools/convert/map/Door.java
- src/toniarts/openkeeper/tools/modelviewer/ModelViewer.java
- src/toniarts/openkeeper/utils/AssetUtils.java
- src/toniarts/openkeeper/view/KeeperHand.java
- src/toniarts/openkeeper/world/ThingLoader.java
- src/toniarts/openkeeper/world/WorldState.java
- src/toniarts/openkeeper/world/animation/AnimationControl.java
- src/toniarts/openkeeper/world/animation/AnimationLoader.java
- src/toniarts/openkeeper/world/control/IUnitFlowerControl.java
- src/toniarts/openkeeper/world/control/UnitFlowerControl.java
- src/toniarts/openkeeper/world/creature/CreatureControl.java
- src/toniarts/openkeeper/world/creature/CreatureFlowerControl.java
- src/toniarts/openkeeper/world/creature/CreatureLoader.java
- src/toniarts/openkeeper/world/creature/pathfinding/MapIndexedGraph.java
- src/toniarts/openkeeper/world/door/DoorControl.java
- src/toniarts/openkeeper/world/door/DoorLoader.java
- src/toniarts/openkeeper/world/object/ObjectLoader.java
Implements basic door/barricade stuff
> Feature 234

- src/toniarts/openkeeper/world/creature/CreatureControl.java
- src/toniarts/openkeeper/world/creature/CreatureLoader.java
- src/toniarts/openkeeper/world/creature/steering/AbstractCreatureSteeringControl.java
- src/toniarts/openkeeper/world/creature/steering/CreatureSteeringCreator.java
added ReachOrientation steering (now work better than was)
> New Steering test two

- assets/Interface/GameHUD.xml
- assets/Interface/MyControls.xml
- src/toniarts/openkeeper/Main.java
- src/toniarts/openkeeper/game/player/PlayerCreatureControl.java
- src/toniarts/openkeeper/game/state/IPlayerScreenController.java
- src/toniarts/openkeeper/game/state/PlayerScreenController.java
- src/toniarts/openkeeper/game/state/PlayerState.java
- src/toniarts/openkeeper/gui/nifty/CreatureCardControl.java
- src/toniarts/openkeeper/gui/nifty/WorkerAmountControl.java
- src/toniarts/openkeeper/gui/nifty/WorkerEqualControl.java
- src/toniarts/openkeeper/view/PlayerInteractionState.java
- src/toniarts/openkeeper/world/creature/CreatureControl.java
we need creatures population calculator like workers population calculator
> Pickup from card

- assets/Interface/ConsoleStyle.xml
- assets/Interface/GameHUD.xml
- src/toniarts/openkeeper/game/console/ConsoleState.java
- src/toniarts/openkeeper/game/console/GameConsole.java
Since the console was still unused i gave it a shot and implemented some commands for it.
Debug flag + F11 is still needed.
> Add commands to the console for easier debugging

- assets/Interface/GameHUD.xml
- assets/Interface/MainMenu.xml
- assets/Interface/MyControls.xml
- src/toniarts/openkeeper/game/action/ActionPointState.java
- src/toniarts/openkeeper/game/data/GameResult.java
- src/toniarts/openkeeper/game/state/EndGameState.java
- src/toniarts/openkeeper/game/state/GameState.java
- src/toniarts/openkeeper/game/state/IPlayerScreenController.java
- src/toniarts/openkeeper/game/state/MainMenuScreenController.java
- src/toniarts/openkeeper/game/state/MainMenuState.java
- src/toniarts/openkeeper/game/state/PlayerScreenController.java
- src/toniarts/openkeeper/game/state/PlayerState.java
- src/toniarts/openkeeper/game/trigger/TriggerData.java
- src/toniarts/openkeeper/view/PlayerCameraState.java
- src/toniarts/openkeeper/world/MapLoader.java
added GameHUD objective information
added toggle bottom panel (need redesign)
added debriefing screen (not tested)
added zoom to dungeon from GameHUD
fixed some GameHUD tooltip text (with placeholders)
fixed seldom NPE
> Debriefing and Game HUD

- src/toniarts/openkeeper/game/console/GameConsole.java
- src/toniarts/openkeeper/game/player/PlayerCreatureControl.java
- src/toniarts/openkeeper/game/state/CheatState.java
- src/toniarts/openkeeper/view/PlayerInteractionState.java
- src/toniarts/openkeeper/world/creature/CreatureControl.java
I've added several new commands and also implemented "level up" and "win level" cheats.
> Additional commands

- src/toniarts/openkeeper/game/state/MainMenuScreenController.java
Just found a small thing that might return the wrong element (because the marked element isn't removed yet)
> Small fix for movie list

- assets/Interface/MainMenu.xml
- src/toniarts/openkeeper/game/state/MainMenuScreenController.java
Unlock mpd levels if the preceding level was won
> My pet dungeon level progress

- build.gradle
- src/toniarts/openkeeper/game/data/Settings.java
- src/toniarts/openkeeper/game/state/MainMenuScreenController.java
> Feature 299

- src/toniarts/openkeeper/tools/convert/ConversionUtils.java
> Changed the 8-bit string reading from US-ASCII to Windows-1252

- src/toniarts/openkeeper/game/state/loading/LoadingState.java
- src/toniarts/openkeeper/game/state/loading/MultiplayerLoadingState.java
- src/toniarts/openkeeper/game/state/loading/SingleBarLoadingState.java
- src/toniarts/openkeeper/tools/convert/AssetsConverter.java
- src/toniarts/openkeeper/tools/convert/wad/WadFile.java
Fix long standing bug from WAD file extraction, the file names are not unique and yet we added them to a hashmap. And used this quirky method to acquire the path later to the file entry. Aaaand also the file name reading assumed that the names are in the same order as the files are, which might be true but an assumption nevertheless...
Now everything is a bit more precise regarding the WAD files!
> Bugfix 251

- src/toniarts/openkeeper/gui/Cursor.java
> Fixed bitshift

- src/toniarts/openkeeper/game/controller/room/AbstractRoomController.java
- src/toniarts/openkeeper/game/controller/room/DoubleQuadController.java
- src/toniarts/openkeeper/game/controller/room/FiveByFiveRotatedController.java
- src/toniarts/openkeeper/game/controller/room/PrisonController.java
- src/toniarts/openkeeper/game/controller/room/TempleController.java
- src/toniarts/openkeeper/view/map/construction/DoubleQuadConstructor.java
> Issue 185 fixes

- build.gradle
- src/toniarts/openkeeper/view/selection/SelectionBox.java
> Update jME 3.2.4 -> 3.3 beta & libGDX AI

- src/toniarts/openkeeper/game/controller/GameController.java
- src/toniarts/openkeeper/game/state/GameState.java
- src/toniarts/openkeeper/tools/convert/map/Variable.java
> Fix the availabilities and more descriptive enum members

- src/toniarts/openkeeper/Main.java
- src/toniarts/openkeeper/setup/DKConverter.form
- src/toniarts/openkeeper/setup/DKConverter.java
- src/toniarts/openkeeper/tools/convert/AssetsConverter.java
- src/toniarts/openkeeper/tools/convert/conversion/ConversionTaskManager.java
- src/toniarts/openkeeper/tools/convert/conversion/IConversionTaskProvider.java
- src/toniarts/openkeeper/tools/convert/conversion/graph/BreadthFirstTraverser.java
- src/toniarts/openkeeper/tools/convert/conversion/graph/Graph.java
- src/toniarts/openkeeper/tools/convert/conversion/graph/ITraverser.java
- src/toniarts/openkeeper/tools/convert/conversion/graph/ITraverserAction.java
- src/toniarts/openkeeper/tools/convert/conversion/graph/Node.java
- src/toniarts/openkeeper/tools/convert/conversion/graph/TaskNode.java
- src/toniarts/openkeeper/tools/convert/conversion/task/ConversionTask.java
- src/toniarts/openkeeper/tools/convert/conversion/task/ConvertFonts.java
- src/toniarts/openkeeper/tools/convert/conversion/task/ConvertHiScores.java
- src/toniarts/openkeeper/tools/convert/conversion/task/ConvertMapThumbnails.java
- src/toniarts/openkeeper/tools/convert/conversion/task/ConvertModels.java
- src/toniarts/openkeeper/tools/convert/conversion/task/ConvertMouseCursors.java
- src/toniarts/openkeeper/tools/convert/conversion/task/ConvertPaths.java
- src/toniarts/openkeeper/tools/convert/conversion/task/ConvertSounds.java
- src/toniarts/openkeeper/tools/convert/conversion/task/ConvertTexts.java
- src/toniarts/openkeeper/tools/convert/conversion/task/ConvertTextures.java
- src/toniarts/openkeeper/tools/convert/conversion/task/IConversionTask.java
- src/toniarts/openkeeper/tools/convert/conversion/task/IConversionTaskUpdate.java
Yeah, nothing too fancy. Multithreaded asset conversion. For me it cut the conversion time form 7 minutes to 6 minutes. The truth is that we still just need to wait for the models & textures to be converted. Textures could maybe be threaded further as its own task. But I wouldn't bother.
The UI suffered a bit. I didn't want to invest to that too much. Since we might be moving to SWT etc. Maybe the code is now more clearer. Smaller classes and clearer responsibilities.
> Asset conversion

- assets/MatDefs/Gui/ProgressIndicator.j3md
- assets/Shaders/Gui/ProgressIndicator.frag
- assets/Shaders/Gui/ProgressIndicator.vert
- src/toniarts/openkeeper/gui/nifty/jme/ProgressIndicatorPicture.java
- src/toniarts/openkeeper/gui/nifty/jme/ResearchEffectControl.java
- src/toniarts/openkeeper/gui/nifty/jme/SimpleJmeControl.java
We have a 3D engine, act like it :) Much faster solution
> Research shader

- src/toniarts/openkeeper/gui/CursorFactory.java
- src/toniarts/openkeeper/utils/MapThumbnailGenerator.java
- src/toniarts/openkeeper/video/TgqPlayer.java
Better double checked locking. Removed some locks altogether, the classes are still thread safe. But doing this optimistic caching instead of locking and volatiles. Once initialized, they should perform better than the old. And our current usages are single threaded anyway, so there is no penalty now.
> Removed some locks and usages of volatile

- src/toniarts/openkeeper/Main.java
- src/toniarts/openkeeper/game/state/GameClientState.java
- src/toniarts/openkeeper/game/state/PlayerScreenController.java
- src/toniarts/openkeeper/game/state/PlayerState.java
- src/toniarts/openkeeper/game/trigger/TriggerControl.java
Also fixes the level resource bundle. Now the level translations should display ok between changing levels.
> Non persistent playerstate

- build.gradle
- src/toniarts/openkeeper/game/console/ConsoleState.java
- src/toniarts/openkeeper/game/state/GameClientState.java
- src/toniarts/openkeeper/game/state/PlayerScreenController.java
- src/toniarts/openkeeper/game/state/PlayerState.java
- src/toniarts/openkeeper/gui/nifty/NiftyUtils.java
- src/toniarts/openkeeper/gui/nifty/WorkerAmountControl.java
- src/toniarts/openkeeper/gui/nifty/WorkerEqualControl.java
> Memory fixes

- src/toniarts/openkeeper/game/controller/CreaturesController.java
- src/toniarts/openkeeper/game/controller/DoorsController.java
- src/toniarts/openkeeper/game/controller/GameWorldController.java
- src/toniarts/openkeeper/game/controller/MapController.java
- src/toniarts/openkeeper/game/controller/ObjectsController.java
- src/toniarts/openkeeper/game/controller/TrapsController.java
- src/toniarts/openkeeper/game/data/Keeper.java
- src/toniarts/openkeeper/game/logic/DungeonHeartConstruction.java
- src/toniarts/openkeeper/game/map/MapData.java
- src/toniarts/openkeeper/tools/convert/map/KwdFile.java
Resolves #288 
Really it was working in the new design already. But we did load all the objects for everybody. Now only that is missing is the destruction of the dungeon heart. But that actually seems to be done with effects....... So let's see to implement that there.
> Feature 288

- src/toniarts/openkeeper/Main.java
- src/toniarts/openkeeper/cinematics/Cinematic.java
- src/toniarts/openkeeper/game/controller/GameController.java
- src/toniarts/openkeeper/game/controller/ObjectsController.java
- src/toniarts/openkeeper/game/controller/RoomControllerFactory.java
- src/toniarts/openkeeper/game/controller/room/HeroGateFrontEndController.java
- src/toniarts/openkeeper/game/state/GameClientState.java
- src/toniarts/openkeeper/game/state/MainMenuState.java
- src/toniarts/openkeeper/tools/convert/map/KwdFile.java
- src/toniarts/openkeeper/view/PlayerEntityViewState.java
- src/toniarts/openkeeper/view/PlayerInteractionState.java
- src/toniarts/openkeeper/view/control/ObjectViewControl.java
- src/toniarts/openkeeper/view/map/construction/HeroGateFrontEndConstructor.java
Main menu is now loader like a level, since our new architecture works like this... Also animates some objects...
> Main menu to new maploader

- build.gradle
Small thing but just that I remember
> New plugin syntax

- assets/MatDefs/UnitFlower.j3md
- assets/Shaders/UnitFlower.frag
- assets/Shaders/UnitFlower.vert
- build.gradle
- src/toniarts/openkeeper/game/state/SoundState.java
- src/toniarts/openkeeper/tools/modelviewer/SoundsLoader.java
- src/toniarts/openkeeper/utils/MapThumbnailGenerator.java
- src/toniarts/openkeeper/utils/Utils.java
- src/toniarts/openkeeper/view/control/CreatureFlowerControl.java
- src/toniarts/openkeeper/view/control/UnitFlowerControl.java
Greatly improves level startup time (the first frame draws unit flowers for all entities) and displaying unit flowers wont cripple the FPS anymore.
Shaderwise maybe not super optimal coding but ok attempt :D
Resolves #227
> Feature 227

- src/toniarts/openkeeper/tools/convert/BufferedResourceReader.java
- src/toniarts/openkeeper/tools/convert/ByteArrayResourceReader.java
- src/toniarts/openkeeper/tools/convert/FileResourceReader.java
- src/toniarts/openkeeper/tools/convert/ISeekableResourceReader.java
- src/toniarts/openkeeper/tools/convert/KmfModelLoader.java
- src/toniarts/openkeeper/tools/convert/kmf/KmfFile.java
- src/toniarts/openkeeper/tools/convert/map/KwdFile.java
- src/toniarts/openkeeper/tools/convert/sound/SFChunk.java
- src/toniarts/openkeeper/tools/convert/sound/SFFile.java
- src/toniarts/openkeeper/tools/convert/sound/SdtFile.java
- src/toniarts/openkeeper/tools/convert/sound/sfx/SfxMapFile.java
- src/toniarts/openkeeper/tools/convert/spr/SprFile.java
- src/toniarts/openkeeper/tools/convert/str/MbToUniFile.java
- src/toniarts/openkeeper/tools/convert/str/StrFile.java
- src/toniarts/openkeeper/tools/convert/textures/enginetextures/EngineTexturesFile.java
- src/toniarts/openkeeper/tools/convert/wad/WadFile.java
- src/toniarts/openkeeper/video/MovieMaterial.java
- src/toniarts/openkeeper/video/tgq/EAAudioFrame.java
- src/toniarts/openkeeper/video/tgq/TgqFile.java
- src/toniarts/openkeeper/video/tgq/TgqFrame.java
Adds a BufferedInputStream based resource reader that just goes forward. Meant for resources we read completely, from start to end. No need to worry about chunk sizes and all that. The minimum file read is determined by the BufferedInputStream which is sufficiently performant in all cases.
Mainly for the TGQ video and KMF models.
> More io stuff

- build.gradle
Some general improvements as well as new LWJGL 3 version
> Update jME to 3.5 stable

- .github/workflows/gradle.yml
- README.md
Allows to download the builds from the Actions tab.
https://github.com/Trass3r/OpenKeeper/actions/runs/1745813856
> upload build artifacts

- build.gradle
> Update jME to latest version

- src/toniarts/openkeeper/audio/plugins/decoder/MpxReader.java
- src/toniarts/openkeeper/game/controller/GameWorldController.java
- src/toniarts/openkeeper/game/state/MainMenuState.java
- src/toniarts/openkeeper/game/task/TaskManager.java
- src/toniarts/openkeeper/tools/convert/KmfModelLoader.java
- src/toniarts/openkeeper/tools/modelviewer/Debug.java
- src/toniarts/openkeeper/utils/WorldUtils.java
- src/toniarts/openkeeper/view/control/EntityViewControl.java
- src/toniarts/openkeeper/view/control/UnitFlowerControl.java
- src/toniarts/openkeeper/view/map/MapViewController.java
- src/toniarts/openkeeper/view/map/Water.java
Probably super marginal stuff but nice... From Deepsource analysis
> Some minor performance fixes

- .github/workflows/gradle.yml
- .vscode/extensions.json
- .vscode/launch.json
- .vscode/settings.json
- .vscode/tasks.json
Add VSCode files and upgrade CI actions to fix the warnings.
> build setup

- src/toniarts/openkeeper/game/state/MainMenuScreenController.java
> Load default anisotropic filtering in settings on the first run

- src/toniarts/openkeeper/tools/convert/AssetsConverter.java
- src/toniarts/openkeeper/tools/convert/KmfModelLoader.java
> Fix #434 null buffer in mergeGeometries

- build.gradle
Doesn't seem to cause any issues, mainly newer LWJGL 3 here
> jME 3.6 -> 3.6.1

- src/toniarts/openkeeper/video/tgq/TgqFile.java
Reduces nesting a lot.
Closes #443
> Refactor to reduce complexity

- src/toniarts/openkeeper/game/controller/room/storage/RoomGoldControl.java
> Check if the wanted coordinate is actually valid for dropping gold

- src/toniarts/openkeeper/video/TgqPlayer.java
Small fix that we always wait for the audio thread to clean up the audio before we return. On low end machines we can only open one at the time. We may fail on some subsequent action since the audio might be busy.
> Wait that the audio thread has cleaned up the audio resources

- src/toniarts/openkeeper/game/task/TaskManager.java
Faster at removing, a tad slower in sorting. We remove more.
> Use linked list as we tend to remove items from it more
