src/toniarts/opendungeonkeeper/world/room/HeroGateFrontEnd.java

- Convert else if to switch
- level 6b was broken (didn't raise on mouse hover)
- levels with variation had one additional model (level 6a + b had level 6) which force closed the application (nullpointer exception, because the briefing text wasn't there). This is now in the default case.

Fix campaign level selection

---

src/toniarts/openkeeper/cinematics/Cinematic.java

As the clipping distance is pretty high on jmonkey, objects get pretty fast cut through which makes some ugly graphic issues.
Before:
After:
The example was achieved by setting the y component to 0 instead of 0.35f on Line 64.
See also:
http://hub.jmonkeyengine.org/t/how-to-set-the-camera-near-clipping-distance/17661

make camera clipping distance a little shorter

---

assets/Interface/MainMenu.xml
src/toniarts/openkeeper/game/state/MainMenuState.java

As the title already says this commit should implement the original credit list from Dungeon Keeper 2.
Todo list:
Fixes #55

Implement the credit list

---

assets/Interface/MainMenu.xml

At first i tried to unify the position of the cancel and ok button, since they always keep the same position in dk2. The campaign level selection should now look a little bit better since the images aren't aligned to left anymore.

Gui improvements

---

src/toniarts/openkeeper/setup/DKConverter.java
src/toniarts/openkeeper/tools/convert/AssetsConverter.java

- Remove process number from enum and calculate it dynamicly (so we don't
have to care about it if we add/remove items)
- Use the correct number of total conversions needed (was always 8 (max) before)
- Fixed progress of path conversion, since the number was never incremented it stayed 0 all the time

Refactor conversion process

---

src/toniarts/openkeeper/Main.java

This pull request is focused on resolving occurrences of Sonar rules
squid:UselessParenthesesCheck - Useless parentheses around expressions should be removed to prevent any misunderstanding.
squid:S1213 - The members of an interface declaration or class should appear in a pre-defined order.
squid:S1066 - Collapsible "if" statements should be merged.
You can find more information about the issue here:
https://dev.eclipse.org/sonar/rules/show/squid:UselessParenthesesCheck
https://dev.eclipse.org/sonar/rules/show/squid:S1213
https://dev.eclipse.org/sonar/rules/show/squid:S1066
Please let me know if you have any questions.
George Kankava

Multiple code improvements - squid:UselessParenthesesCheck, squid:S1213, squid:S1066

---

src/toniarts/openkeeper/audio/plugins/decoder/BitStream.java
src/toniarts/openkeeper/audio/plugins/decoder/BitrateVariation.java
src/toniarts/openkeeper/audio/plugins/decoder/Frame.java
src/toniarts/openkeeper/audio/plugins/decoder/LayerIDecoder.java
src/toniarts/openkeeper/audio/plugins/decoder/LayerIIDecoder.java
src/toniarts/openkeeper/audio/plugins/decoder/MpxReader.java
src/toniarts/openkeeper/audio/plugins/decoder/Output.java

This pull request is focused on resolving occurrence of Sonar rule
squid:S1854 - Dead stores should be removed.
You can find more information about the issue here:
https://dev.eclipse.org/sonar/rules/show/squid:S1854
Please let me know if you have any questions.
George Kankava

squid:S1854 - Dead stores should be removed

---

src/toniarts/openkeeper/game/trigger/TriggerActionData.java
src/toniarts/openkeeper/game/trigger/TriggerControl.java
src/toniarts/openkeeper/game/trigger/TriggerData.java

This pull request is focused on resolving occurrences of Sonar rules
squid:CommentedOutCodeLine - Sections of code should not be "commented out".
squid:S1066 - Collapsible "if" statements should be merged.
squid:S1596 - Collections.emptyList(), emptyMap() and emptySet() should be used instead of Collections.EMPTY_LIST, EMPTY_MAP and EMPTY_SET.
squid:S1068 - Unused private fields should be removed.
You can find more information about the issue here:
https://dev.eclipse.org/sonar/rules/show/squid:CommentedOutCodeLine
https://dev.eclipse.org/sonar/rules/show/squid:S1066
https://dev.eclipse.org/sonar/rules/show/squid:S1596
https://dev.eclipse.org/sonar/rules/show/squid:S1068
Please let me know if you have any questions.
George Kankava

Multiple code improvements - squid:CommentedOutCodeLine, squid:S1066, squid:S1596, squid:S1068

---

src/toniarts/openkeeper/tools/modelviewer/ModelViewer.java

The EffectManagerState used another KWD variable (the class variable) rather than the local variable.
This caused NullPointerExceptions when loading a Map.

Fixed NPE in ModelViewer when viewing a Map

---

src/toniarts/openkeeper/tools/modelviewer/ModelViewer.java

This is an issue in ModelViewer when selecting Terrain in the top dropdown, and a room type in the list dropdown (e.g. Treasury or Lair), these don't have children, so a NPE was produced when the getChild(0) call is done on these.

check if spat has children before we try to get them

---

.gitignore
assets/Interface/GameHUD.xml
assets/Interface/MainMenu.xml
assets/Interface/MyControls.xml
assets/Interface/ScrollbarSmallStyle.xml
src/toniarts/openkeeper/game/state/GameState.java
src/toniarts/openkeeper/game/state/SystemMessageState.java
src/toniarts/openkeeper/game/trigger/TriggerControl.java
src/toniarts/openkeeper/gui/nifty/SystemMessageControl.java
src/toniarts/openkeeper/gui/nifty/message/MessageBoxControl.java
src/toniarts/openkeeper/gui/nifty/message/SystemMessageControl.java

Resolves #220 
This is a basic implementation of the system messages. Currently it only shows the scripted (triggered) speeches of the mentor. I also using now a smaller scrollbar, which fits the theme better than the big one of the main menu.
I found several things that should be fixed to make this work flawlessly:
1. The player interaction needs to be revamped. The gui recognition is more a guess than a correct determination (it tries to figure out the viewport). Therefore the cursor isn't correct and a implementation of the tooltip doesn't make sense because it would overwritten immediately.
2. Focusing things isn't implemented right now (like the first creature appearance which can be overwritten like in the first level)

Implement system messages

---

src/toniarts/openkeeper/game/player/PlayerTriggerControl.java
src/toniarts/openkeeper/game/state/SoundState.java
src/toniarts/openkeeper/view/PlayerCameraState.java
src/toniarts/openkeeper/world/WorldState.java

This add system messages when a creature enters for the first time the dungeon.
If the introduction override is set, it will display a custom message and play the corresponding mentor speech (like for the goblin in level 1).

Creature messages

---

src/toniarts/openkeeper/game/state/MainMenuState.java
src/toniarts/openkeeper/tools/convert/AssetsConverter.java
src/toniarts/openkeeper/utils/AssetUtils.java

This clean the folders where the assets are stored before a new conversion is happening. This should avoid having the need to manually remove the assets.
Since we don't really respect custom models / textures (because they may be overwritten in the conversion process anyway) yet i see it less problematic right now.

Clean asset folders before converting

---

assets/Interface/GameHUD.xml
assets/Interface/MyControls.xml

Not all changes from
https://github.com/tonihele/OpenKeeper/commit/73983d6e8d316c17942c2695aed7083e285963bc
where restored in
https://github.com/tonihele/OpenKeeper/commit/775fd294f31a574eac65a213ef3eb95e0840bd2f
Even though it never crashed, it showed several NPEs in the console log since the ids of some elements weren't correct, leaving the creature tab complely useless (ALL creatures had their own card and thus couldn't be picked up and the imp count was always zero).
Also rearranged the secondary click for the imps, since nifty seem to dislike if its defined before the primary.

Fix creature cards

---

src/toniarts/openkeeper/game/data/Level.java
src/toniarts/openkeeper/game/data/Settings.java
src/toniarts/openkeeper/game/state/MainMenuScreenController.java

This implements the missing check for the movie list. Movies can now be unlocked via winning a campaign level or by adding `LEVEL_STATUS7(string)=COMPLETED` in the user properties (only if you are a cheater 😉)

Movie unlock

---

src/toniarts/openkeeper/tools/convert/textures/enginetextures/EngineTexturesFile.java

saves space and also makes them usable in DK2

save opaque textures as RGB pngs

---

LICENSE

Adds a GitHub GPL-3.0 license so Github can auto-detect the license. Existing `license.txt` remains unchanged and available in the root of the repository for IDE's.
Reported in: https://github.com/tonihele/OpenKeeper/issues/346

[ISSUE-346] Add GPL-3.0 LICENSE

---

src/toniarts/openkeeper/tools/convert/AssetsConverter.java
src/toniarts/openkeeper/tools/convert/FontCreator.java
src/toniarts/openkeeper/tools/convert/IResourceReader.java
src/toniarts/openkeeper/tools/convert/bf4/Bf4File.java
src/toniarts/openkeeper/tools/convert/conversion/task/ConvertFonts.java
src/toniarts/openkeeper/tools/convert/conversion/task/ConvertModels.java
src/toniarts/openkeeper/tools/convert/conversion/task/ConvertTextures.java
src/toniarts/openkeeper/utils/Utils.java

Makes the fonts used in-game as power of two for maximum compatibility. Also the Japanese fonts are really big, or rather numerous in character count. In lieu support multi-paged fonts and cap the page/texture size to 2048 (also compatibility thing). The implementation is pretty naive and tries to approximate used space and page counts. It works with the given material _perfectly_. Even if it would fail to calculate, it can accommodate to extra page needs dynamically. All the fancy gimmicks are only visible with the Japanese edition. Plain English version fits to single pages.
The font conversion is fairly slow process but it seems to scale fairly well. It is now multi-threaded. Also the actual font resource reading should now have less read counts which should provide some speed boost.

Font compatibility

---

src/toniarts/openkeeper/tools/convert/AssetsConverter.java
src/toniarts/openkeeper/tools/convert/FontCreator.java

Apply the font paging / space saving to all calculated sizes. With the basic English version of the game, we save around 1,5 million pixels (all fonts summed). We can probably use those somewhere else.

Font space

---

src/toniarts/openkeeper/Main.java
src/toniarts/openkeeper/audio/plugins/MP2Loader.java
src/toniarts/openkeeper/game/state/PlayerScreenController.java
src/toniarts/openkeeper/tools/convert/conversion/task/ConvertFonts.java
src/toniarts/openkeeper/tools/convert/conversion/task/ConvertMapThumbnails.java
src/toniarts/openkeeper/tools/convert/conversion/task/ConvertTextures.java
src/toniarts/openkeeper/tools/convert/textures/enginetextures/EngineTexturesFile.java
src/toniarts/openkeeper/utils/AssetUtils.java
src/toniarts/openkeeper/utils/MapThumbnailGenerator.java
src/toniarts/openkeeper/world/effect/TorchControl.java

Use ImageIO with buffers, both read and write. Also disable the cache (or rather default to memory cache instead of disk cache). Our audio reader was really heavy reader, now it also uses buffered stream. 
All this makes things a bit more light weight, and it does show... but of course it is not a miracle maker.

Buffered io

---

src/toniarts/openkeeper/tools/convert/AssetsConverter.java
src/toniarts/openkeeper/tools/convert/textures/ImageUtil.java
src/toniarts/openkeeper/tools/convert/textures/enginetextures/EngineTexturesFile.java
src/toniarts/openkeeper/tools/convert/textures/loadingscreens/LoadingScreenFile.java

Tried to speed up the texture conversion but it seems that going with rasters and whatnots  doesn't make any difference here. At least it looks that way. So this PR just ends up unifying the image creation from the engine textures (including the .444 files). For the .444 this changes things, we now leave out the alpha channel if it is not present (it is _never_ present, these are the big loading and title screens). This saves us about 5% disk space, and small speed boosts from not writing and later needing to read that information.
Small code unification and tiny speed boost.

Texture conversion

---

build.gradle
gradlew

Removes all the warnings and deprecations from the build. Upgrades the 3rd party libraries now available from MavenCentral.
Gradle 7 is not yet too well supported so that will be later then. Maybe together with Java 17...

Gradle 7 compatible

---

src/toniarts/openkeeper/game/task/AbstractTask.java
src/toniarts/openkeeper/game/task/Task.java
src/toniarts/openkeeper/game/task/objective/ObjectiveTaskDecorator.java
src/toniarts/openkeeper/tools/convert/IResourceChunkReader.java
src/toniarts/openkeeper/tools/convert/ResourceChunkReader.java
src/toniarts/openkeeper/tools/convert/map/KwdFile.java

Use the _new_ Java Date/Time API... from Java 8. Sorry for being such a late bloomer :)
Tasks now use Instant rather than Date. This is actually a kinda bug fix even. The tasks could even go broke when automatically changing DST. Or in the future loading a saved game on another timezone, or just changing your timezone... Well, you get the drift, using date here is just stupid, always was.
What comes to KWD timestamps... This has been broken all along.
- We assumed that the timestamp is in UTC. I tried this with the map editor. The timestamp is always the local time. And there is no timezone information (that I'm aware of). So we have no way of actually getting accurate timestamp.
- The months actually are from 1-12. With the old API 0-11 is assumed. The month was always off by one.
- …

Use the new Java Date/Time API

---

src/toniarts/openkeeper/game/controller/creature/CreatureController.java

Small fix in custom maps etc. where some animations are overridden. Basically disabling the state I guess. Fixes NPE.

Don't crash if there is no animation for a state

---

src/toniarts/openkeeper/animation/PoseTrack.java
src/toniarts/openkeeper/tools/convert/AssetsConverter.java
src/toniarts/openkeeper/tools/convert/KmfModelLoader.java
src/toniarts/openkeeper/tools/modelviewer/ModelViewer.java
src/toniarts/openkeeper/view/animation/AnimationLoader.java
src/toniarts/openkeeper/view/animation/LoopMode.java
src/toniarts/openkeeper/view/map/construction/FiveByFiveRotatedConstructor.java
src/toniarts/openkeeper/view/map/construction/HeroGateFrontEndConstructor.java

Found this old #362 branch and rebased fwiw.

 Migrate to the new animation system

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
gradlew.bat
settings.gradle

This should (re-)enable automatic JDK download on Gradle 8.x. Eases up setting up OpenKeeper

Gradle 8.5 -> 8.6 and automatic JDK resolution
